// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: advertisers.sql

package database

import (
	"context"
)

const createAdvertiser = `-- name: CreateAdvertiser :one
INSERT INTO advertisers (name, url, logo, description, phone, email, address, city, state, zip, country) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING id, name, url, logo, description, phone, email, address, city, state, zip, country, is_active, is_deleted, is_verified, is_approved, is_featured, created_at, updated_at
`

type CreateAdvertiserParams struct {
	Name        string `json:"name"`
	Url         string `json:"url"`
	Logo        string `json:"logo"`
	Description string `json:"description"`
	Phone       string `json:"phone"`
	Email       string `json:"email"`
	Address     string `json:"address"`
	City        string `json:"city"`
	State       string `json:"state"`
	Zip         string `json:"zip"`
	Country     string `json:"country"`
}

func (q *Queries) CreateAdvertiser(ctx context.Context, arg CreateAdvertiserParams) (Advertiser, error) {
	row := q.db.QueryRow(ctx, createAdvertiser,
		arg.Name,
		arg.Url,
		arg.Logo,
		arg.Description,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Country,
	)
	var i Advertiser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Logo,
		&i.Description,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Country,
		&i.IsActive,
		&i.IsDeleted,
		&i.IsVerified,
		&i.IsApproved,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAdvertiser = `-- name: DeleteAdvertiser :one
DELETE FROM advertisers WHERE id = $1 RETURNING id, name, url, logo, description, phone, email, address, city, state, zip, country, is_active, is_deleted, is_verified, is_approved, is_featured, created_at, updated_at
`

func (q *Queries) DeleteAdvertiser(ctx context.Context, id int32) (Advertiser, error) {
	row := q.db.QueryRow(ctx, deleteAdvertiser, id)
	var i Advertiser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Logo,
		&i.Description,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Country,
		&i.IsActive,
		&i.IsDeleted,
		&i.IsVerified,
		&i.IsApproved,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdvertiserByID = `-- name: GetAdvertiserByID :one
SELECT id, name, url, logo, description, phone, email, address, city, state, zip, country, is_active, is_deleted, is_verified, is_approved, is_featured, created_at, updated_at FROM advertisers WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAdvertiserByID(ctx context.Context, id int32) (Advertiser, error) {
	row := q.db.QueryRow(ctx, getAdvertiserByID, id)
	var i Advertiser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Logo,
		&i.Description,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Country,
		&i.IsActive,
		&i.IsDeleted,
		&i.IsVerified,
		&i.IsApproved,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllAdvertisers = `-- name: GetAllAdvertisers :many
SELECT id, name, url, logo, description, phone, email, address, city, state, zip, country, is_active, is_deleted, is_verified, is_approved, is_featured, created_at, updated_at FROM advertisers WHERE is_active = TRUE AND is_deleted = FALSE
`

func (q *Queries) GetAllAdvertisers(ctx context.Context) ([]Advertiser, error) {
	rows, err := q.db.Query(ctx, getAllAdvertisers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Advertiser
	for rows.Next() {
		var i Advertiser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Logo,
			&i.Description,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Country,
			&i.IsActive,
			&i.IsDeleted,
			&i.IsVerified,
			&i.IsApproved,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdvertiser = `-- name: UpdateAdvertiser :one
UPDATE advertisers SET name = $2, url = $3, logo = $4, description = $5, phone = $6, email = $7, address = $8, city = $9, state = $10, zip = $11, country = $12 WHERE id = $1 RETURNING id, name, url, logo, description, phone, email, address, city, state, zip, country, is_active, is_deleted, is_verified, is_approved, is_featured, created_at, updated_at
`

type UpdateAdvertiserParams struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Url         string `json:"url"`
	Logo        string `json:"logo"`
	Description string `json:"description"`
	Phone       string `json:"phone"`
	Email       string `json:"email"`
	Address     string `json:"address"`
	City        string `json:"city"`
	State       string `json:"state"`
	Zip         string `json:"zip"`
	Country     string `json:"country"`
}

func (q *Queries) UpdateAdvertiser(ctx context.Context, arg UpdateAdvertiserParams) (Advertiser, error) {
	row := q.db.QueryRow(ctx, updateAdvertiser,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Logo,
		arg.Description,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Country,
	)
	var i Advertiser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Logo,
		&i.Description,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Country,
		&i.IsActive,
		&i.IsDeleted,
		&i.IsVerified,
		&i.IsApproved,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
