// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Advertiser struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Url         string           `json:"url"`
	Logo        string           `json:"logo"`
	Description string           `json:"description"`
	Phone       string           `json:"phone"`
	Email       string           `json:"email"`
	Address     string           `json:"address"`
	City        string           `json:"city"`
	State       string           `json:"state"`
	Zip         string           `json:"zip"`
	Country     string           `json:"country"`
	IsActive    bool             `json:"is_active"`
	IsDeleted   bool             `json:"is_deleted"`
	IsVerified  bool             `json:"is_verified"`
	IsApproved  bool             `json:"is_approved"`
	IsFeatured  bool             `json:"is_featured"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
