// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	CreateAdvertiser(ctx context.Context, arg CreateAdvertiserParams) (Advertiser, error)
	DeleteAdvertiser(ctx context.Context, id int32) (Advertiser, error)
	GetAdvertiserByID(ctx context.Context, id int32) (Advertiser, error)
	GetAllAdvertisers(ctx context.Context) ([]Advertiser, error)
	UpdateAdvertiser(ctx context.Context, arg UpdateAdvertiserParams) (Advertiser, error)
}

var _ Querier = (*Queries)(nil)
